CREATE TABLE PAIS ( COD_PAIS NUMBER PRIMARY KEY,
                    NOME VARCHAR2(30));
                    
CREATE TABLE ESTADO ( COD_ESTADO NUMBER PRIMARY KEY,
                    NOME VARCHAR2(30),
                    COD_PAIS NUMBER);
                    
ALTER TABLE ESTADO AND CONSTRAINT FK_ESTADO FOREIGN KEY (COD_PAIS) REFERENCES PAIS (COD_PAIS);

CREATE TABLE CIDADE ( COD_CIDADE NUMBER PRIMARY KEY,
                    NOME VARCHAR2(30),
                    COD_ESTADO NUMBER);

ALTER TABLE CIDADE AND CONSTRAINT FK_CIDADE FOREIGN KEY (COD_ESTADO) REFERENCES PAIS (COD_ESTADO);

CREATE TABLE BAIRRO ( COD_BAIRRO NUMBER PRIMARY KEY,
                    NOME VARCHAR2(30);
                    COD_CIDADE NUMBER);
                    
ALTER TABLE BAIRRO AND CONSTRAINT FK_BAIRRO FOREIGN KEY (COD_CIDADE) REFERENCES PAIS (COD_CIDADE);